export const cities = [
  { name: "Kyiv", country: "UA" },
  { name: "Warsaw", country: "PL" },
  { name: "Barcelona", country: "ES" },
  { name: "Tokyo", country: "JP" },
  { name: "Berlin", country: "DE" },
  { name: "New York", country: "US" },
  { name: "Paris", country: "FR" },
  { name: "London", country: "GB" },
  { name: "Amsterdam", country: "NL" },
  { name: "Rome", country: "IT" },
  { name: "Sydney", country: "AU" },
  { name: "Los Angeles", country: "US" },
  { name: "Toronto", country: "CA" },
  { name: "Hong Kong", country: "HK" },
  { name: "Singapore", country: "SG" },
  { name: "Dubai", country: "AE" },
  { name: "San Francisco", country: "US" },
  { name: "Seoul", country: "KR" },
  { name: "Bangkok", country: "TH" },
  { name: "Shanghai", country: "CN" },
  { name: "Copenhagen", country: "DK" },
];
